theme: jekyll-theme-minimal
collections:
  project:
    output: true
    permalink: /project/:title/
  tech:
    output: true
    permalink: /tech/:title/
  job:
    output: true
    permalink: /job/:title/
defaults:
  - scope:
      path: ""
      type: "project"
    values:
      layout: default
  - scope:
      path: ""
      type: "tech"
    values:
      layout: default
  - scope:
      path: ""
      type: "job"
    values:
      layout: default
plugins:
  - jekyll-last-modified-at
