# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Last Modified Date
        run: |
          find _project _tech _job -name '*.md' -print0 | while IFS= read -r -d '' file; do
            # Only update if `last_modified_at` doesn't match the last commit date
            if grep -q '^last_modified_at:' "$file"; then
              if ! grep -q "^last_modified_at: $last_modified" "$file"; then
                sed -i "s/^last_modified_at:.*/last_modified_at: $last_modified/" "$file"
                git add "$file"
              fi
            else
              sed -i "1i last_modified_at: $last_modified" "$file"
              git add "$file"
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
